language: go
go:
- 1.16.x
script:
- make testacc
deploy:
- provider: script
  skip_cleanup: true
  script:
  - make release
  on:
    tags: true
env:
  global:
    secure: sWseOcPS8ErsZGTSVpo1C2PNv/nJoiEH1CXi3MqVgt+zJKcibHeKbv8i3Ux9A8US+j5YoWyxTwK1TJQJjzL9oXGYc/0hhteC5/QmxI3/YENnar3D3oco8jFtTSaDshKdKlNB4QiC9cMPMglGAOvhjGdKhbNu1chJzBrYkKmntKf5M0Iokeu1b7G36BpOVGUAHPgR77BdJ7GZwCL7O2llsswHPqi7iHL+dL2yoq459SoUNJBv3t0CiV1GGwY4dCMNpUpPB3i/njEku9m8BZAyhZRFhJ+N9Z1XzrmTVgT9/1hIdR2VzPJj9XT+ytli88hXPqMy86P+MmrSjFtX8o2uLoO3w0EgR4MD00QGVQ1tJbFco75KxPENpr5FAF6QvuT5rpinCXMtfHjvGVazVyHkEddriaA756xBc86V9kNKTFHt1gsHE5L5VV7gy0AyB+eHLmUz2x516a5ax4WomluiJKRrhs0uXuXsTlOO+cqU5tdbIKx1tlQsvIy8qHVXY5QwKzYo7cToeO501WPJFN7ok0bkSD4e+3aT6CvqgdyF/3/Kf2Kk8IaVsvJJ2G6700cXJ7Q0r16H74jgbKB4XYd2lMac/1eq4KsV6xpygOVUcJ0D1AZbE6MvhzUM8oUGJIhSzPpTCXFbLD1BbKexULTsiYBuOgldPKUIPhQO//8qkgc=
